apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
images:
- name: ai-safeguard
  newName: 853310098537.dkr.ecr.eu-central-1.amazonaws.com/ai-safeguard
  newTag: main-af952a63-1690795444
